### PR TITLE
Update link to current Scala documentation

### PR DESCRIPTION
**Pull request by sbrunk**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @sbrunk,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
LGTM, thanks a lot! 
I'll merge right away once you click through the CLA agreement online (you confirm it via a github account).

**Comment by sbrunk** [comment]
Ah, didn't think of that. Now confirmed.

**Comment by ktoso** [comment]
Thanks a lot!

**Pull request merged**
